# Generated by Django 4.2.3 on 2023-07-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeverInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
                ('cpu_num', models.CharField(max_length=5)),
                ('cpu_percent', models.CharField(max_length=30)),
                ('memory', models.CharField(max_length=30)),
                ('memory_total', models.CharField(max_length=30)),
                ('memory_ava', models.CharField(max_length=30)),
                ('memory_per', models.CharField(max_length=30)),
                ('disk_total', models.CharField(max_length=30)),
                ('disk_free', models.CharField(max_length=30)),
                ('net_sent', models.CharField(max_length=30)),
                ('net_rec', models.CharField(max_length=30)),
            ],
        ),
    ]
