# Generated by Django 4.2.3 on 2023-10-09 02:07

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeverInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('license_name', models.CharField(blank=True, max_length=30, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('guest', models.CharField(blank=True, max_length=30, null=True)),
                ('guest_nice', models.CharField(blank=True, max_length=30, null=True)),
                ('idle', models.CharField(blank=True, max_length=30, null=True)),
                ('iowait', models.CharField(blank=True, max_length=30, null=True)),
                ('irq', models.CharField(blank=True, max_length=30, null=True)),
                ('nice', models.CharField(blank=True, max_length=30, null=True)),
                ('percent', models.CharField(blank=True, max_length=30, null=True)),
                ('softirq', models.CharField(blank=True, max_length=30, null=True)),
                ('steal', models.CharField(blank=True, max_length=30, null=True)),
                ('system', models.CharField(blank=True, max_length=30, null=True)),
                ('total_active', models.CharField(blank=True, max_length=30, null=True)),
                ('total_idle', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.CharField(blank=True, max_length=30, null=True)),
                ('count', models.CharField(blank=True, max_length=5, null=True)),
                ('free_physics', models.CharField(blank=True, max_length=30, null=True)),
                ('free_swap', models.CharField(blank=True, max_length=30, null=True)),
                ('processes', models.CharField(blank=True, max_length=30, null=True)),
                ('total_physics', models.CharField(blank=True, max_length=30, null=True)),
                ('total_swap', models.CharField(blank=True, max_length=30, null=True)),
                ('uptime', models.CharField(blank=True, max_length=30, null=True)),
                ('used_physics', models.CharField(blank=True, max_length=30, null=True)),
                ('used_swap', models.CharField(blank=True, max_length=30, null=True)),
                ('ava', models.CharField(blank=True, max_length=30, null=True)),
                ('memory_percent', models.CharField(blank=True, max_length=30, null=True)),
                ('swap_percent', models.CharField(blank=True, max_length=30, null=True)),
                ('free', models.CharField(blank=True, max_length=30, null=True)),
                ('mount_point', models.CharField(blank=True, max_length=30, null=True)),
                ('total', models.CharField(blank=True, max_length=30, null=True)),
                ('used', models.CharField(blank=True, max_length=30, null=True)),
                ('disk_percent', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(max_length=50, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
