# Generated by Django 4.2.3 on 2023-07-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_on_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='severinfo',
            old_name='cpu_num',
            new_name='cpu_count',
        ),
        migrations.RenameField(
            model_name='severinfo',
            old_name='disk_free',
            new_name='disk_percent',
        ),
        migrations.RenameField(
            model_name='severinfo',
            old_name='memory',
            new_name='disk_used',
        ),
        migrations.RenameField(
            model_name='severinfo',
            old_name='memory_ava',
            new_name='mem_used',
        ),
    ]
