# Generated by Django 4.2.3 on 2023-07-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_on_server', '0002_rename_cpu_num_severinfo_cpu_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='severinfo',
            name='cpu_count',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='severinfo',
            name='cpu_percent',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='severinfo',
            name='disk_percent',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='severinfo',
            name='disk_total',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='severinfo',
            name='disk_used',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='severinfo',
            name='ip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='severinfo',
            name='mem_used',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='severinfo',
            name='memory_per',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='severinfo',
            name='memory_total',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='severinfo',
            name='net_rec',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='severinfo',
            name='net_sent',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
