# Generated by Django 4.2.3 on 2023-10-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_on_server', '0002_alter_severinfo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='severinfo',
            name='license_name',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
