# Generated by Django 4.2.3 on 2023-09-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_on_server', '0003_alter_severinfo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='severinfo',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
