# Generated by Django 4.2.3 on 2023-08-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_on_server', '0004_severinfo_memory_ava'),
    ]

    operations = [
        migrations.AddField(
            model_name='severinfo',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
