# Generated by Django 4.2.3 on 2023-09-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_on_server', '0005_severinfo_loadavg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='severinfo',
            name='alter_query',
        ),
    ]
