# Generated by Django 4.2.3 on 2023-08-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_on_server', '0005_severinfo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='severinfo',
            old_name='net_rec',
            new_name='cpu_guest_nice',
        ),
        migrations.RenameField(
            model_name='severinfo',
            old_name='net_sent',
            new_name='cpu_idle',
        ),
        migrations.AddField(
            model_name='severinfo',
            name='cpu_iowait',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='cpu_irq',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='cpu_nice',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='cpu_softirq',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='cpu_steal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='cpu_system',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='cpu_total_active',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='cpu_total_idle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='cpu_user',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='disk_free',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='disk_mount_point',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='guest',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='memory_free_physics',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='memory_free_swap',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='memory_processes',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='memory_total_physics',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='memory_total_swap',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='memory_uptime',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='memory_used_physics',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severinfo',
            name='memory_used_swap',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
