# Generated by Django 4.2.3 on 2023-08-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_on_server', '0006_rename_net_rec_severinfo_cpu_guest_nice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('license_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
