# Generated by Django 4.2.3 on 2023-08-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_on_server', '0007_licensename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='severinfo',
            old_name='guest',
            new_name='cpu_guest',
        ),
        migrations.RemoveField(
            model_name='severinfo',
            name='status',
        ),
    ]
