# Generated by Django 4.2.3 on 2023-10-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_on_server', '0008_rename_percent_severinfo_cpu_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='severinfo',
            old_name='cpu_percent',
            new_name='percent',
        ),
    ]
