# Generated by Django 4.2.3 on 2023-08-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_on_server', '0009_delete_licensename_rename_ip_severinfo_license_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='severinfo',
            name='time',
        ),
    ]
