# Generated by Django 4.2.3 on 2023-08-10 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eye_on_server', '0010_remove_severinfo_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='severinfo',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
