# Generated by Django 4.2.3 on 2023-08-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_on_server', '0012_severinfo_memory_swap_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='severinfo',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
