# Generated by Django 4.2.3 on 2023-08-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_on_server', '0013_alter_severinfo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='severinfo',
            name='time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
