# Generated by Django 4.2.3 on 2023-08-28 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_on_server', '0015_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
